BEGIN;

CREATE TABLE IF NOT EXISTS Roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    UNIQUE (id),
    UNIQUE (name)
);

-- Delete the 'role' column from the 'QuestionSets' table
ALTER TABLE QuestionSets DROP COLUMN role;

-- Add the 'roleId' column to the 'QuestionSets' table as a BIGINT
ALTER TABLE QuestionSets ADD COLUMN roleId BIGINT;

-- Create the foreign key relationship with the 'Roles' table
ALTER TABLE QuestionSets
ADD CONSTRAINT fk_questionsets_roles FOREIGN KEY (roleId) REFERENCES Roles(id);

COMMIT;