BEGIN;

CREATE TABLE IF NOT EXISTS JobTypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    UNIQUE (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS Jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    questionSetId BIGINT NOT NULL,
    employerId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    jobTypeId BIGINT NOT NULL,
    description TEXT NOT NULL,
    UNIQUE (id),
    CONSTRAINT fk_jobs_employers FOREIGN KEY (employerId) REFERENCES Employers(id),
    CONSTRAINT fk_jobs_roles FOREIGN KEY (roleId) REFERENCES Roles(id),
    CONSTRAINT fk_jobs_jobtypes FOREIGN KEY (jobTypeId) REFERENCES JobTypes(id),
    CONSTRAINT fk_jobs_questionsets FOREIGN KEY (questionSetId) REFERENCES QuestionSets(id)
);

COMMIT;
