BEGIN;

CREATE TABLE IF NOT EXISTS Feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    questionSetId BIGINT NOT NULL,
    practiceSessionId BIGINT NOT NULL,
    questionIds BIGINT ARRAY NOT NULL,
    videoUrls TEXT ARRAY NOT NULL,
    feedbacks TEXT ARRAY NOT NULL,
    created_at TIMESTAMP NOT NULL,
    seen BOOLEAN NOT NULL,
    UNIQUE (id),
    FOREIGN KEY (userId) REFERENCES Users(id),
    FOREIGN KEY (questionSetId) REFERENCES QuestionSets(id),
    FOREIGN KEY (practiceSessionId) REFERENCES PracticeSessions(id)
);

COMMIT;