BEGIN;

ALTER TABLE PracticeSessions DROP CONSTRAINT IF EXISTS chk_practicesessions_status;
ALTER TABLE PracticeSessions ADD CONSTRAINT chk_practicesessions_status CHECK (status IN ('in_progress', 'completed', 'closed'));

ALTER TABLE PracticeSessions DROP CONSTRAINT IF EXISTS chk_practicesessions_completedat;
ALTER TABLE PracticeSessions ADD CONSTRAINT chk_practicesessions_completedat CHECK (completedAt IS NULL OR status = 'completed' OR status = 'closed');

CREATE TABLE IF NOT EXISTS Feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    questionSetId BIGINT NOT NULL,
    practiceSessionId BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    seen BOOLEAN NOT NULL,
    UNIQUE (id),
    CONSTRAINT fk_feedback_users FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT fk_feedback_questionsets FOREIGN KEY (questionSetId) REFERENCES QuestionSets(id),
    CONSTRAINT fk_feedback_practicesessions FOREIGN KEY (practiceSessionId) REFERENCES PracticeSessions(id)
);

CREATE TABLE IF NOT EXISTS FeedbackEntries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedbackId BIGINT NOT NULL,
    questionId BIGINT NOT NULL,
    videoUrl TEXT NOT NULL,
    feedbackText TEXT NOT NULL,
    CONSTRAINT fk_feedbackentries_feedback FOREIGN KEY (feedbackId) REFERENCES Feedback(id),
    CONSTRAINT fk_feedbackentries_questions FOREIGN KEY (questionId) REFERENCES Questions(id)
);

COMMIT;