BEGIN;

-- Remove the added columns
ALTER TABLE IF EXISTS Users
DROP COLUMN IF EXISTS school,
DROP COLUMN IF EXISTS major,
DROP COLUMN IF EXISTS employer,
DROP COLUMN IF EXISTS position,
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS resume;

COMMIT;
