BEGIN;

CREATE TABLE IF NOT EXISTS PracticeSessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    questionSetId BIGINT NOT NULL,
    status TEXT NOT NULL,
    lastAnsweredQuestionId BIGINT,
    completedAt TIMESTAMP,
    UNIQUE (id),
    CONSTRAINT fk_practicesessions_users FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT fk_practicesessions_questionsets FOREIGN KEY (questionSetId) REFERENCES QuestionSets(id),
    CONSTRAINT fk_practicesessions_questions FOREIGN KEY (lastAnsweredQuestionId) REFERENCES Questions(id),
    CONSTRAINT chk_practicesessions_status CHECK (status IN ('in_progress', 'completed')),
    CONSTRAINT chk_practicesessions_completedat CHECK (completedAt IS NULL OR status = 'completed')
);

CREATE TABLE IF NOT EXISTS PracticeSessionSubmissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practiceSessionId BIGINT NOT NULL,
    questionId BIGINT NOT NULL,
    url TEXT NOT NULL,
    UNIQUE (id),
    CONSTRAINT fk_practicesessionsubmissions_practicesessions FOREIGN KEY (practiceSessionId) REFERENCES PracticeSessions(id),
    CONSTRAINT fk_practicesessionsubmissions_questions FOREIGN KEY (questionId) REFERENCES Questions(id)
);

COMMIT;

