BEGIN;

CREATE TABLE IF NOT EXISTS Users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    middle_name TEXT,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    type_of_user TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_login TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    UNIQUE (id, email)  
);

COMMIT;